/* Generated By:JavaCC: Do not edit this line. PDDLFormulaeParserConstants.java */
package org.mcm.sws.pddl;

public interface PDDLFormulaeParserConstants {

  int EOF = 0;
  int NUMBER = 6;
  int DEFINE = 7;
  int DOMAIN_TOKEN = 8;
  int PROBLEM = 9;
  int REQUIREMENTS = 10;
  int STRIPS = 11;
  int TYPING = 12;
  int NEGATIVE_PRECONDITIONS = 13;
  int DISJUNCTIVE_PRECONDITIONS = 14;
  int EQUALITY = 15;
  int EXISTENTIAL_PRECONDITIONS = 16;
  int UNIVERSAL_PRECONDITIONS = 17;
  int QUANTIFIED_PRECONDITIONS = 18;
  int CONDITIONAL_EFFECTS = 19;
  int FLUENTS = 20;
  int ADL = 21;
  int DURATIVE_ACTIONS = 22;
  int DURATION_INEQUALITIES = 23;
  int CONTINUOUS_EFFECTS = 24;
  int TYPES = 25;
  int CONSTANTS = 26;
  int PREDICATES = 27;
  int ACTION = 28;
  int DURATIVE_ACTION = 29;
  int PARAMETERS = 30;
  int DURATION = 31;
  int PRECONDITION = 32;
  int CONDITION = 33;
  int EFFECT = 34;
  int PDOMAIN = 35;
  int OBJECTS = 36;
  int INIT = 37;
  int GOAL = 38;
  int METRIC = 39;
  int OBJECT_TOKEN = 40;
  int EITHER = 41;
  int WHEN = 42;
  int NOT = 43;
  int AND = 44;
  int OR = 45;
  int IMPLY = 46;
  int EXISTS = 47;
  int FORALL = 48;
  int AT = 49;
  int OVER = 50;
  int START = 51;
  int END = 52;
  int ALL = 53;
  int MINIMIZE = 54;
  int MAXIMIZE = 55;
  int TOTAL_TIME = 56;
  int ACHIEVE = 57;
  int FINDOUT = 58;
  int ASSIGN = 59;
  int INCREASE = 60;
  int DECREASE = 61;
  int SCALE_UP = 62;
  int SCALE_DOWN = 63;
  int NAME = 64;
  int DURATION_VAR = 65;
  int VARIABLE = 66;
  int LE = 67;
  int GE = 68;
  int L = 69;
  int G = 70;
  int EQ = 71;
  int ADD = 72;
  int SUB = 73;
  int DIV = 74;
  int MUL = 75;
  int IDENT = 76;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<NUMBER>",
    "\"define\"",
    "\"domain\"",
    "\"problem\"",
    "\"requirements\"",
    "\":strips\"",
    "\":typing\"",
    "\":negative-preconditions\"",
    "\":disjunctive-preconditions\"",
    "\":equality\"",
    "\":existential-preconditions\"",
    "\":universal-preconditions\"",
    "\":quantified-preconditions\"",
    "\":conditional-effects\"",
    "\":fluents\"",
    "\":adl\"",
    "\":durative-actions\"",
    "\":duration-inequalities\"",
    "\":continuous-effects\"",
    "\":types\"",
    "\":constants\"",
    "\":predicates\"",
    "\":action\"",
    "\":durative-action\"",
    "\":parameters\"",
    "\":duration\"",
    "\":precondition\"",
    "\":condition\"",
    "\":effect\"",
    "\":domain\"",
    "\":objects\"",
    "\":init\"",
    "\":goal\"",
    "\":metric\"",
    "\"object\"",
    "\"either\"",
    "\"when\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"imply\"",
    "\"exists\"",
    "\"forall\"",
    "\"at\"",
    "\"over\"",
    "\"start\"",
    "\"end\"",
    "\"all\"",
    "\"minimize\"",
    "\"maximize\"",
    "\"total-time\"",
    "\"achieve\"",
    "\"findout\"",
    "\"assign\"",
    "\"increase\"",
    "\"decrease\"",
    "\"scale-up\"",
    "\"scale-down\"",
    "<NAME>",
    "\"?duration\"",
    "<VARIABLE>",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "<IDENT>",
    "\"(\"",
    "\")\"",
  };

}
